### ISSUE TITLE
How to get Correlation ID inside the view function in FastAPI?

### ISSUE THREAD

**Issue by raghavsikaria** [snok/asgi-correlation-id#11]
Hey author, thanks for the amazing work! Our team is planning to onboard this library in our projects.
I have been trying to retrieve the created correlation ID inside a view function in FastAPI but I am not able to query it somehow. I have tried querying the `request.headers` and `request.body()`, and am still not able to find it.
How can I get that?

**Comment by sondrelg** [comment]
Hi @raghavsikaria! You should be able to get the correlation ID value by doing this:

```python
from asgi_correlation_id.context import correlation_id as correlation_id_context_var

correlation_id = correlation_id_context_var.get()
```

Just put the last line inside your view function 👍

**Comment by raghavsikaria** [comment]
Oh, great thanks! So let's say I have a couple of thousand concurrent requests hitting that particular endpoint. Will I get the correct correlation ID for each of their contexts this way?

**Comment by sondrelg** [comment]
Yes you will! 

That's why we decided to use [context vars](https://docs.python.org/3/library/contextvars.html) to store this type of state - each request should get its own ID, and the ID should be accessible anywhere in your application code 👍  That's the intention at least, but feel free to test it out and report back 🙂

**Comment by raghavsikaria** [comment]
Cool, thanks for the prompt help!

**Comment by sondrelg** [comment]
No worries, happy to see others using the package 👏  

Feel free to star the repo if you find it helpful, as it will help raise our visibility a little 🙂

**Comment by raghavsikaria** [comment]
Done, sure. My Bad!
