### ISSUE TITLE
Requests containing UUID in standard form should be parsed 

### ISSUE THREAD

**Issue by matusvalo** [snok/asgi-correlation-id#12]
## Reproduction steps
1. Start simple app logging correlation ID on localhost port 8000
2. send request with Correlation ID in standard form:
```
curl -v -H "X-Request-ID: $(uuidgen)" localhost:8000
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.64.1
> Accept: */*
> X-Request-ID: 611AEE7D-1206-4E03-A2A6-97C238D982FD
```
## Actual result
Application logs following truncated Request ID: `611AEE7D-1206-4E03-A2A6-97C238D9`

## Expected result
Application should log non-truncated Request ID sent by application: `611AEE7D-1206-4E03-A2A6-97C238D982FD`

## Root cause
Library is not parsing Request ID in header:
https://github.com/snok/asgi-correlation-id/blob/c427439342ba4e1809cf4dcb9b3bb693bb156518/asgi_correlation_id/middleware.py#L46
 Hence, in case of the UUID is valid but not in hex format is causing library to truncate  UUID incorrectly here:
 https://github.com/snok/asgi-correlation-id/blob/c427439342ba4e1809cf4dcb9b3bb693bb156518/asgi_correlation_id/log_filters.py#L21

**Comment by sondrelg** [comment]
Hi @matusvalo, thanks for opening an issue!

As you point out, the request ID here is valid:
```python
is_valid_uuid('611AEE7D-1206-4E03-A2A6-97C238D982FD')
Out[4]: True
```

Just so I don't misunderstand anything, are you proposing that we - when receiving a valid UUID, should transform it to a hex format like this?

```python
UUID('611AEE7D-1206-4E03-A2A6-97C238D982FD').hex
Out[5]: '611aee7d12064e03a2a697c238d982fd'
```

**Comment by matusvalo** [comment]
The problem is that by default the UUID is truncated in logs because line  

https://github.com/snok/asgi-correlation-id/blob/c427439342ba4e1809cf4dcb9b3bb693bb156518/asgi_correlation_id/log_filters.py#L21

expects UUID in hex format.

**Comment by matusvalo** [comment]
@sondrelg  I have created a PR which fixes this issue. I hope that the issue will be more clear after.
