### ISSUE TITLE
Can you please give an example of how to add parent id and current process id in celery tasks for loguru?

### ISSUE THREAD

**Issue by lakshaythareja** [snok/asgi-correlation-id#18]
I use loguru for logging, saw your example for adding the correlation id for requests. But I am unable to add parent and current process id for celery tasks in loguru. 
Can you help?

**Comment by sondrelg** [comment]
Yes! 🙂 See https://github.com/snok/asgi-correlation-id/issues/7 - that should have a few examples you can use 👍 Feel free to re-open if you get stuck

**Comment by lakshaythareja** [comment]
As i mentioned the issue above solves for correlation id in a request and not parent and current process id for celery tasks. I need help there.

**Comment by sondrelg** [comment]
Ah, sorry, it's too early in the morning 😄 I'll try to find the time to look into this later today

**Comment by sondrelg** [comment]
I think something like this might do the trick:

```python
import logging
import sys
from uuid import uuid4

import uvicorn
from asgi_correlation_id import CorrelationIdMiddleware
from asgi_correlation_id.context import correlation_id, celery_parent_id, celery_current_id
from fastapi import FastAPI
from loguru import logger

app = FastAPI()

app.add_middleware(CorrelationIdMiddleware)

logger.remove()


def correlation_id_filter(record):
    celery_current_id.set(uuid4())  # just for testing - remove these
    celery_parent_id.set(uuid4())  # just for testing - remove these
    record['correlation_id'] = correlation_id.get()
    record['celery_parent_id'] = str(celery_parent_id.get())[:6]
    record['celery_current_id'] = str(celery_current_id.get())[:6]
    return record['correlation_id']


fmt = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> <level>{level:<8}</level> <red>{correlation_id}</red> <red>{celery_parent_id}-{celery_current_id}</red> <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

logger.add(
    sys.stderr,
    format=fmt,
    level=logging.DEBUG,
    filter=correlation_id_filter,
)


@app.get('/')
def index():
    logger.info("Request with id ")
    return 'OK'


if __name__ == '__main__':
    uvicorn.run(app)
```

**Comment by sondrelg** [comment]
This is what it looks like in my local environment
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/25310870/153450754-9b98c75e-d4a9-4f42-a53a-a1a6fbb6dcd2.png">

**Comment by lakshaythareja** [comment]
It worked thanks.

**Comment by stdedos** [comment]
@sondrelg would you mind adding https://github.com/snok/asgi-correlation-id/issues/18#issuecomment-1035118784 in the Readme? 🙏

**Comment by sondrelg** [comment]
I'd be happy to accept a PR if you want to create one @stdedos!
