### ISSUE TITLE
The headers with same key are overwritten

### ISSUE THREAD

**Issue by lakshaythareja** [snok/asgi-correlation-id#22]
Starlette responses adds cookies as headers with the same key.
`        self.raw_headers.append((b"set-cookie", cookie_val.encode("latin-1")))
`

In your middleware handle outgoing request over writes the same key with only the last value.
```python
        async def handle_outgoing_request(message: Message) -> None:
            if message['type'] == 'http.response.start':
                headers = {k.decode(): v.decode() for (k, v) in message['headers']}
                headers[self.header_name] = correlation_id.get()
                headers['Access-Control-Expose-Headers'] = self.header_name
                response_headers = Headers(headers=headers)
                message['headers'] = response_headers.raw
            await send(message)
```

**Comment by lakshaythareja** [comment]
Lets say my header list contains a list with keys as set cookies and values
as access_token, refresh_token(diff entries).
Then it just keeps the last refresh token and doesn't keep the first value
of access token.

**Comment by sondrelg** [comment]
But this middleware does not set a `set-cookie` header. Are you referring to another header being overwritten?

**Comment by lakshaythareja** [comment]
Yes it overrides other headers.

**Comment by sondrelg** [comment]
Could you open a PR with a failing test to illustrate what is wrong? I'm not able to replicate the issue on my own

**Comment by lakshaythareja** [comment]
You can check this image, here in message there are 4 headers with key as set-cookie and different values:
![image](https://user-images.githubusercontent.com/51370699/158200289-388c102e-2663-4b35-85b9-89a20751301b.png)

``` headers = {k.decode(): v.decode() for (k, v) in message['headers']}```
replaces the same key with different values with just 1 key and 1 value.

**Comment by sondrelg** [comment]
I see. That seems worth fixing! Would you be interested in creating a PR with a fix? 🙂

**Comment by lakshaythareja** [comment]
[https://github.com/snok/asgi-correlation-id/pull/25](url)

**Comment by lakshaythareja** [comment]
@sondrelg can you please merge the PR and release a new version I will then start using it.

**Comment by sondrelg** [comment]
Yes I'll review it early tomorrow morning (~15 hours from now) 👍 Thanks for the effort @lakshaythareja
