### ISSUE TITLE
Conda 

### ISSUE THREAD

**Issue by ludaavics** [snok/asgi-correlation-id#60]
Hi,

Would you consider making your library available on conda? 
Thanks!

**Comment by sondrelg** [comment]
Hi @ludaavics :slightly_smiling_face: What does that entail?

**Comment by ludaavics** [comment]
I haven't gone through the process yet, but I think it should be [pretty straightforward](https://conda-forge.org/docs/maintainer/adding_pkgs.html#generating-the-recipe)?
I'm happy to take an initial stab at it, create the PR to conda-forge, listing you as maintainer, and ping you on the relevant PR.

**Comment by sondrelg** [comment]
That would be great! :+1:

**Comment by ludaavics** [comment]
https://github.com/conda-forge/staged-recipes/pull/21362

**Comment by ludaavics** [comment]
@sondrelg could you please  comment on the PR above to confirm that you're OK being the maintainer for the conda recipe? thanks!

**Comment by sondrelg** [comment]
I guess this is implemented. What are the implications of this @ludaavics? Do I need to update the release workflows to push/trigger anything? 

If not, I guess we might be able to close this?

**Comment by ludaavics** [comment]
My understanding is that every pypi release should automatically be released on conda now.
Just need to address anything that may come up on the feedstock repo where we're both marked as maintainers
