### ISSUE TITLE
default_value no longer allowed in filter configuration

### ISSUE THREAD

**Issue by jslvtr** [snok/asgi-correlation-id#72]
Hello!

The docs suggest having a filter configuration like this:

```python
'filters': {  # correlation ID filter must be added here to make the %(correlation_id)s formatter work
	'correlation_id': {
		'()': 'asgi_correlation_id.CorrelationIdFilter',
		'uuid_length': 8 if not settings.ENVIRONMENT == 'local' else 32,
		'default_value': '-',
	},
}
```

But I've found that including `default_value` results in an error. Removing it makes it work. I can't see `default_value` listed as a parameter in the `CorrelationIdFilter`. Maybe it's been removed, and the documentation should be updated? Or did I misunderstand something?

Thanks!

**Comment by tlinhart** [comment]
What package version you have installed? The support for filter default value was added just recently, in version 4.1.0.

**Comment by jslvtr** [comment]
Ah! That makes sense, I've got 4.0.0.

Thank you!

Kind regards,
Jose

**Comment by sondrelg** [comment]
Heh, unexpected race condition :sweat_smile:

**Comment by jslvtr** [comment]
Oh, I see it was released 20 min ago 😂
