### ISSUE TITLE
bug in the docs

### ISSUE THREAD

**Issue by vamos777q** [snok/asgi-correlation-id#75]
Hey,

It looks like there was a bug which was recently introduced if you follow the setup as described in the documentation.

This import does not exist any more:
from asgi_correlation_id import correlation_id_filter
so this line:
cid_filter = correlation_id_filter(uuid_length=32)
should change to this:
cid_filter = CorrelationIdFilter(uuid_length=32)

**Comment by JonasKs** [comment]
Good catch 😊 Would you like to submit a PR to fix it? 😊
If you have questions on how to do so, let us know and we’ll provide detailed steps.

**Comment by vamos777q** [comment]
thanks. I've never done that before, but I am willing to try if you send me instructions.

**Comment by sondrelg** [comment]
If you edit the README in the Github UI directly, you can commit to a new branch and open a PR 😊 Think that's the simplest way

**Comment by vamos777q** [comment]
Sorry, it looks like the README is ok, and only the blogpost which it points too (on medium) should be fixed.
[](https://medium.com/@sondrelg_12432/setting-up-request-id-logging-for-your-fastapi-application-4dc190aac0ea)

I put not there when I came across it initially, but since it's on Medium only you can fix it. My first PR will need to wait :) 

Thanks
