### ISSUE TITLE
Weird issues with Correlation id... thread safety maybe?

### ISSUE THREAD

**Issue by evinism** [snok/asgi-correlation-id#8]
Started trying to use this on a server -- started getting a large set of these errors: `Generating new UUID, since header value '035873B9-9CBC_AC14000A-0050_6196BA3C_5350B2D7-1A16' is invalid `.  Those UUID valuess are complete nonsense, so I'm a tad confused. Locally, the project worked fine, and this error occurred on maybe 50% of the requests under a reasonable load.

Additionally, I was getting weird looking values in `x-request-id`:

```
x-request-id: 0351335E-5C3E_AC14010B-0050_6196B87B_530A0198-560B
```

Env: Python 3.6, gunicorn, fastapi

Middleware installed via:
```py
app = FastAPI(middleware=[Middleware(CorrelationIdMiddleware)])
```

**Comment by evinism** [comment]
Here's a list of the invalid header values I got. Weird patterns in there: https://gist.githubusercontent.com/evinism/46780060605fa63ceda50ad86c907b39/raw/bc0f36d9253b9290ffdb73485d3a462dd3a363a5/weird_uuids.txt

**Comment by sondrelg** [comment]
Hi!

If you look at the code [here](https://github.com/snok/asgi-correlation-id/blob/main/asgi_correlation_id/middleware.py#L43), what we're doing is actually very simple. We validate the incoming UUID and if it fails UUID-validation (you can disable validation - it's a setting), we generate a new one using `uuid4().hex`.

This `uuid4` function is a python core library, so I'd be surprised if there was anything wrong with the code in general, but is it possible that your setup is doing something unexpected?

Can you run this code locally?
```python
>>> from uuid import uuid4
>>> uuid4().hex
'7ced06b713a640e0ad732bee6abde5ec'
```

```python
>>> from uuid import UUID
>>> is_valid_uuid('035873B9-9CBC_AC14000A-0050_6196BA3C_5350B2D7-1A16')
False
```

And what headers are you sending in exactly?

**Comment by evinism** [comment]
OHHHHH Sorry about that! You're so right -- X-Request-ID is being sent as a header to begin with!!

My bad!!

**Comment by sondrelg** [comment]
No problem. Glad it resolved itself 🙂
