### ISSUE TITLE
Allow config option to require valid correlation id

### ISSUE THREAD

**Issue by benm5678** [snok/asgi-correlation-id#85]
When passing an invalid correlation id or omitting it, it seems this framework just generates one.
I'd like a config option to cause it to fail in those cases (as it's an indicator something is wrong in our flow & if we just generate a random now, it won't be connected to the real correlation id coming from the front end client).

**Comment by sondrelg** [comment]
How would you define "cause it to fail"? Are you aware that there is a warning log emitted when validation fails?

**Comment by benm5678** [comment]
It'd be nice if it throws an HttpException in that case (400 Bad Request sounds like a good option).  I would rather it fail & we fix it, then going on for some time without realizing there's an issue.  But definitely it should be configurable...I can't imagine it's the desired behavior in every app.

**Comment by sondrelg** [comment]
It sounds like this might make sense for your isolated use-case, but from my perspective it's not something that would add enough value to this middleware to implement. I suggest you write your own custom middleware to validate and reject requests with improper headers 👍

**Comment by benm5678** [comment]
It's actually the main point of this package, and it would be more powerful for more use cases if had that options.  But sure, we'll for and use our own.  Thanks!

**Comment by JonasKs** [comment]
I agree with Sondre here, this is not a security middleware. A valid UUID shouldn't be a security implementation or assumption the request is sent from your frontend.

**Comment by benm5678** [comment]
> I agree with Sondre here, this is not a security middleware. A valid UUID shouldn't be a security implementation or assumption the request is sent from your frontend.

Not looking to rely on it for security.  The option I asked for helps you avoid situations where some change is done on the front end/initiator app that perhaps causes invalid or omitted correlation ids, from corrupting your trace data.  We would rather have the app break in those cases, and fix it.  I already forked it, and implemented quickly -- when I pass it None for generator, it will throw Http 400 exception if no valid uuid is passed in request.
