### ISSUE TITLE
Default inbound correlation-id validator is incorrect?

### ISSUE THREAD

**Issue by dmder** [snok/asgi-correlation-id#89]
```python
from asgi_correlation_id.middleware import is_valid_uuid4

# returns True but I expected it to return False since 
# '00000000000000000000000000000000' is not a valid version 4 UUID
is_valid_uuid4(uuid.UUID(int=0).hex)  
```

This is because `uuid.UUID('00000000000000000000000000000000', version=4)` returns `UUID('00000000-0000-4000-8000-000000000000')`.

I suspect this should rather be something like `UUID(uuid_).version == 4`

**Comment by sondrelg** [comment]
Hmm, yes that seems right @dmder. Would you be interested in creating a PR with the fix?
