### ISSUE TITLE
Publish package on PyPi for 3.11 and 3.12

### ISSUE THREAD

**Issue by mathijssh** [snok/asgi-correlation-id#98]
Hi there - I'm developing an API on py312 and would love to use `asgi_correlation_id`, would it be possible to get the package published on PyPi for python versions greater than 3.10? 

Let me know, thanks!

mathijssh

P.S. if there's a way in which I can contribute to this myself, please let me know, happy to help!

**Comment by sondrelg** [comment]
We don't build a wheel per version, but the code should be usable for all Python version above 3.8. In other words, if you run `pip install asgi-correlation-id` it should work on 3.12. Did you run into a problem with this? 

I noticed you snake_cased the name. Did you perhaps try to install the wrong target?
